site_name: CLM Day ISLM Handson
site_url: https://sap-clm-sl.github.io/ISLM/
theme:
  name: material
  logo: images/CLMDDaylogo.png
  palette:
    - scheme: default
      primary: orange
      accent: purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.progressbar
  - attr_list
  - md_in_html
  - tables
  - attr_list
nav:
  - Welcome: "index.md"

  - Custom Gen AI Use Cases in SAP S/4HANA: "ISLM_with_SAPGenAI/README.md"
  - Predict the number of first class seats occupied in a flight: "ISLM_with_HANAML/README.md"
  - Predict the plane type of an aircraft: "ISLM_with_SAPAIServices_BTP/README.md"
