site_name: CLM Day 2025 - ISLM Handson
site_url: https://sap-clm-sl.github.io/ISLM/
theme:
  name: material
  logo: assets/clm-day-banner.png
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: indigo
      accent: indio
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer

markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.progressbar
  - attr_list
  - md_in_html
  - tables
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Getting Started:
      - Welcome: "index.md"
      - Tutorials: "Gettingstarted/tutorials.md"
  - Gen AI: "ISLM_with_SAPGenAI/README.md"
  - APL: "ISLM_with_HANAML/README.md"
  - DAR: "ISLM_with_SAPAIServices_BTP/README.md"
  - Community:
      - Blogs: "community/readme.md"
      - Videos: "community/videos.md"

  - Contact us: "Contactus/readme.md"
  - Feedback: "feedback/readme.md"

extra:
  generator: false # Hides "Made with MkDocs"
  legal: |
    © 2025 Your Company • Powered by Gen AI 🚀
