name: Build and Deploy Documentation using MkDocs

on:
  push:
    branches:
      - main

  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies and setup git config
        if: "!contains(github.event.head_commit.message, ':gear:')"
        run: |
          git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
          git fetch
          git branch --remote
          git push origin --delete gh-pages
      - name: Clean Build
        run: |
          pip install mkdocs-material
          pip install mkdocs
          mkdocs build --clean
          mkdocs gh-deploy --force --clean
      - name: Publish Pages
        run: |
          curl -s -X POST \
          -H "Accept: application/vnd.github.switcheroo-preview+json" -H "Authorization: token ${{ secrets.PERFMONBOT_USER_TOKEN }}" \
          https://sap-clm-sl.github.io/ISLM/pages \
          -d '{"source":{"branch":"gh-pages","path":"/"}}'
